name = "MoscariniPostelVinay2016"
uuid = "10fa9cbd-1cb2-44a2-b001-07453a0f30f4"
authors = ["PATRASBastien <bastien.patras@sciencespo.fr> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
